export const REMOTE_REVEAL_WRAPPED_PASSWORD = import.meta.env.VITE_REMOTE_REVEAL_WRAPPED_PASSWORD as string;

export const REMOTE_REVEAL_URL_TEMPLATE = import.meta.env.VITE_REMOTE_REVEAL_URL_TEMPLATE as string;
