name: Release

on:
  push:
    branches:
      - main

concurrency: release

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: |
          npm ci
          npm run lint
          BASE_PUBLIC_PATH="/secret-santa-pwa/" VITE_REMOTE_REVEAL_WRAPPED_PASSWORD="santa" VITE_REMOTE_REVEAL_URL_TEMPLATE="https://eddmann.com/secret-santa-pwa/#/reveal/{wrapped}" npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
